### ISSUE TITLE
Route returns 404.

### ISSUE THREAD

**Issue by bayareawebpro** [jackabox/nova-duplicate-field#3]
duplicate-field:1 GET http://nova.local/nova-duplicate 404 (Not Found)

```
 DuplicateField::make('Duplicate')->withMeta([
    'id' => $this->id, // id of record
    'resource' => 'pages', // resource url 
    'model' => 'App\Page', // model path
    'relations' => ['tags', 'categories', 'children', 'parents'], // an array of any relations to load (nullable).
])
```

Installed it to give it a try but it failed.  Looks like it's not detecting the panel route.

**Comment by aydot** [comment]
I am getting similar error. How was this fixed?

**Comment by aydot** [comment]
ping @jackabox  @bayareawebpro

**Comment by jackabox** [comment]
What error are your receiving? As long as all of the properties passed through with the meta are correct you shouldn't receive any 404s. Are all of these set correctly?

**Comment by aydot** [comment]
`
DuplicateField::make('Duplicate')
   ->withMeta([
          'resource' => 'posts',
          'model' => 'App\Models\Post',
           'id' => $this->id,
           'relations' => ['user'],
       ]),
`

Getting `Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException`

`Request URL: http://nova-local/nova-duplicate`
`Request Method: GET`
`Status Code: 405 Method Not Allowed`

**Comment by audetcameron** [comment]
I am also getting 405 Method not Allowed,   must be related to CORS?
maybe  this isn't being executed from bootstrap.js in app because it's in nova?

`
import axios from 'axios';
window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';

/**
 * Next we will register the CSRF Token as a common header with Axios so that
 * all outgoing HTTP requests automatically have it attached. This is just
 * a simple convenience so we don't have to attach every token manually.
 */

let token = document.head.querySelector('meta[name="csrf-token"]');

if (token) {
    window.axios.defaults.headers.common['X-CSRF-TOKEN'] = token.content;
} else {
    console.error('CSRF token not found: https://laravel.com/docs/csrf#csrf-x-csrf-token');
}
`

**Comment by cloudbluedigital** [comment]
is there a solution for this? my url seems to look like this not sure why http://localhost//nova/resources/organisations/233

**Comment by audetcameron** [comment]
do you have a trailing /  on your app name in config/app.php?   / .env file?    'localhost'
